query CheckUserExistsWithEmail($email: String!) {
  findUser(input: { email: $email }) {
    __typename
  }
}

query CheckUserExistsWithUsername($username: String!) {
  findUser(input: { username: $username }) {
    __typename
  }
}

mutation SignInWithEmailPassword($input: EmailPasswordSignInInput!) {
  emailPasswordSignIn(input: $input) {
    __typename
    ... on EmailPasswordSignInFailure {
      emailError
      passwordError
      otherError
    }
    ... on EmailPasswordSignInSuccess {
      user {
        id
        username
        email
      }
      token
    }
  }
}

mutation SignUpWithEmailPassword($input: EmailPasswordSignUpInput!) {
  emailPasswordSignUp(input: $input) {
    __typename
    ... on EmailPasswordSignUpFailure {
      usernameError
      emailError
      passwordError
      otherError
    }
    ... on EmailPasswordSignUpSuccess {
      email
    }
  }
}

mutation ResendVerificationEmail($input: ResendVerificationEmailInput!) {
  resendVerificationEmail(input: $input) {
    __typename
    ... on ResendVerificationEmailFailure {
      emailError
      otherError
    }
    ... on ResendVerificationEmailSuccess {
      message
    }
  }
}

mutation VerifyEmail($input: EmailVerificationInput!) {
  verifyEmail(input: $input) {
    __typename
    ... on EmailVerificationFailure {
      tokenError
      emailError
      otherError
    }
    ... on EmailVerificationSuccess {
      user {
        id
        username
        email
        emailVerified
      }
      token
    }
  }
}

mutation ChangePassword($input: ChangePasswordInput!) {
  changePassword(input: $input) {
    __typename
    ... on ChangePasswordFailure {
      newPasswordError
      oldPasswordError
      otherError
    }
    ... on ChangePasswordSuccess {
      message
    }
  }
}

mutation SendResetPasswordEmail($input: SendResetPasswordEmailInput!) {
  sendResetPasswordEmail(input: $input) {
    __typename
    ... on SendResetPasswordEmailFailure {
      emailError
      otherError
    }
    ... on SendResetPasswordEmailSuccess {
      message
    }
  }
}

mutation ResetPassword($input: ResetPasswordInput!) {
  resetPassword(input: $input) {
    __typename
    ... on ResetPasswordFailure {
      tokenError
      newPasswordError
      otherError
    }
    ... on ResetPasswordSuccess {
      message
    }
  }
}

mutation UpdateProfile($input: UpdateProfileInput!) {
  updateProfile(input: $input) {
    __typename
    ... on UpdateProfileFailure {
      nameError
      otherError
    }
    ... on UpdateProfileSuccess {
      updatedProfile {
        id
        name
        bio
      }
    }
  }
}
